MASTER_NAME = 'hsmitsS'
MASTER_IP = '192.168.56.110'

COMMON_VMEM = 4096
COMMON_VCPU = 4

$DISABLE_FIREWALL_SCRIPT = <<-SHELL
  sudo systemctl disable --now firewalld
SHELL

Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT 

    config.vbguest.installer_options = { allow_kernel_upgrade: true }

    config.vm.provider "virtualbox" do |v|
        v.memory = COMMON_VMEM
        v.cpus = COMMON_VCPU
    end

    config.vm.define MASTER_NAME do |master|
        master.vm.hostname = MASTER_NAME
        master.vm.network :private_network, ip: MASTER_IP
        master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        master.vm.provision "shell", privileged: true, path: "scripts/master_setup.sh", args: [MASTER_IP]

        master.vm.provider "virtualbox" do |v|
            v.name = MASTER_NAME
        end
    end
end
